# Generated by Django 3.2.7 on 2021-09-15 14:59

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=50, verbose_name='Nome do autor')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_editora', models.CharField(max_length=50, verbose_name='Nome da editora')),
                ('telefone_editora', models.CharField(max_length=15, verbose_name='Telefone da editora')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, verbose_name='Genero')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('total', models.FloatField(verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=50, verbose_name='Livro')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('estoque', models.IntegerField(verbose_name='Estoque')),
                ('imagem', stdimage.models.StdImageField(upload_to='Livros', verbose_name='Imagem')),
                ('Fk_Autor', models.ManyToManyField(to='livraria.Autor')),
                ('Fk_Editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraria.editora')),
                ('Fk_Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraria.genero')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data')),
                ('Fk_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraria.cliente')),
                ('Fk_ItensVenda', models.ManyToManyField(through='livraria.ItensVenda', to='livraria.Livro')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='Fk_Livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraria.livro'),
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='Fk_Venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraria.venda'),
        ),
    ]
